<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2698b8aa666fab5f7cee758b75f77e35
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'Automattic\\WooCommerce\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Automattic\\WooCommerce\\' => 
        array (
            0 => __DIR__ . '/..' . '/automattic/woocommerce/src/WooCommerce',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2698b8aa666fab5f7cee758b75f77e35::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2698b8aa666fab5f7cee758b75f77e35::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit2698b8aa666fab5f7cee758b75f77e35::$classMap;

        }, null, ClassLoader::class);
    }
}
